name       : nfs-utils
version    : 2.6.3
release    : 19
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/nfs-utils/2.6.3/nfs-utils-2.6.3.tar.gz : d90d6c9c140d576682dda3d2c56982f6830e35d830655e0db5eebe45926523f5
license    : GPL-2.0-or-later
component  : network.utils
summary    :
    - Network File System Utilities
description: |
    Network File System Utilities
replaces   :
    - libnfsidmap
    - devel : libnfsidmap-devel
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(keyutils)
    - pkgconfig(krb5)
    - pkgconfig(libcap)
    - pkgconfig(libevent)
    - pkgconfig(libtirpc)
    - pkgconfig(sqlite3)
    - rpcsvc-proto-devel
rundeps    :
    - rpcbind
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    %configure --disable-static \
               --without-tcp-wrappers \
               --with-pluginpath=%libdir%/libnfsidmap \
               --with-systemd \
               --with-statedir=/run/nfs \
               --disable-sbin-override \
               --enable-libmount-mount \
               --enable-ipv6 \
               --enable-svcgss # Required if gssproxy is not available
build      : |
    %make
install    : |
    %make_install

    install -Dm00644 utils/nfsidmap/id_resolver.conf $installdir/usr/share/defaults/etc/request-key.d/id_resolver.conf
    install -m00644 nfs.conf $installdir/usr/share/defaults/etc/nfs.conf
    install -m00644 support/nfsidmap/idmapd.conf $installdir/usr/share/defaults/etc/idmapd.conf
    install -m00644 utils/mount/nfsmount.conf $installdir/usr/share/defaults/etc/nfsmount.conf

    install -Dm00644 $pkgfiles/nfs-utils.tmpfiles $installdir/%libdir%/tmpfiles.d/nfs-utils.conf

    # Install compat links T10615
    install -D -d -m 00755 $installdir/sbin
    pushd $installdir/usr/sbin
    for FILE in *; do
        ln -sv /usr/sbin/$FILE $installdir/sbin/$FILE
    done

    # Stateless
    rm -v $installdir/run/nfs/etab \
          $installdir/run/nfs/rmtab \
          $installdir/run/nfs/state
    rmdir -v $installdir/run/nfs/sm \
             $installdir/run/nfs/sm.bak \
             $installdir/run/nfs/ \
             $installdir/run/ \
