name       : nfs-utils
version    : 2.1.1
release    : 4
source     :
    - http://internode.dl.sourceforge.net/project/nfs/nfs-utils/2.1.1/nfs-utils-2.1.1.tar.bz2 : 0a28416948516c26f3bfe90425b0de09b79364dc1f508bf1dda8de66e1edbb09
license    : GPL-2.0
summary    : Network File System Utilities
description: |
    Network File System Utilities
component  : network.utils
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(libcap)
    - pkgconfig(libevent)
    - pkgconfig(libnfsidmap)
    - pkgconfig(sqlite3)
rundeps    : |
    - rpcbind
setup      : |
    %configure --without-tcp-wrappers --disable-gss --disable-ipv6 --disable-tirpc --with-systemd=/usr/lib/systemd/system --with-statedir=/run/nfs
build      : |
    %make
install    : |
    %make_install
    install -D -d -m 00755 $installdir/%libdir%/systemd/system/
    install -m 00644 systemd/*.mount systemd/*.target systemd/*.service $installdir/%libdir%/systemd/system/
    # Configure enabling this by default once we have testing!

    # Dirs
    rm -rf $installdir/var
    install -D -m 00644 $pkgfiles/nfs-utils.tmpfiles $installdir/%libdir%/tmpfiles.d/nfs-utils.conf
