name       : nfs-utils
version    : 1.3.3
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/nfs/nfs-utils/1.3.3/nfs-utils-1.3.3.tar.bz2 : fe8e04f7a869975e11765085d27e91ca3f765e08811a527bb4e32056e41176eb
license    : GPL-2.0
summary    : Network File System Utilities
description: |
    Network File System Utilities
builddeps  :
    - pkgconfig(libtirpc)
    - pkgconfig(libevent)
    - libcap2-devel
setup      : |
    %configure --without-tcp-wrappers \
               --disable-nfsv4
build      : |
    %make
install    : |
    %make_install
